#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
	external_bar off:40:0 \
	menubar_opacity 1.0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	display_arrangement_order horizontal \
	window_origin_display default \
	window_placement first_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.03 \
	window_animation_easing ease_in_out_expo \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 3 \
	bottom_padding 3 \
	left_padding 3 \
	right_padding 3 \
	window_gap 06 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

## rules
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^Feishu$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^飞书$" manage=off
yabai -m rule --add app="^飞书会议$" manage=off

## signal
yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.9 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"

echo "yabai configuration loaded.."
