# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# init
export TERM=xterm-256color
export TERM_ITALICS=true
autoload -U colors && colors
export CLICOLOR=1

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
ZSH_THEME="powerlevel10k/powerlevel10k"

# zsh features switch
zstyle ':omz:update' frequency 21
DISABLE_LS_COLORS=true
ENABLE_CORRECTION=true
HIST_STAMPS="yyyy-mm-dd"
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY
setopt ALWAYS_TO_END
setopt COMPLETE_IN_WORD
setopt CDABLE_VARS
setopt PROMPT_SUBST
setopt AUTO_MENU
export HISTSIZE=300
export SAVEHIST=1000
export HISTFILE=~/.zsh_history

zle -N find-in-file
export DEFAULT_USER=$USER
export MANPATH="/usr/local/man:$MANPATH"
export SSH_KEY_PATH="~/.ssh/rsa_id"


plugins=(
	#### inner omz
	z
	common-aliases
	eza
	git
	sudo
	tmux
	shell-proxy
	fzf
	extract
	copybuffer
	copyfile
	copypath
	python
	uv
	kubectl
	docker
	#### from github
	git-open
	fzf-tab
	fzf-tab-source
	zsh-autosuggestions
	zsh-syntax-highlighting
	autoupdate ## auto update custom plugin
)

######################### plugin settings ########################

## eza plugin
zstyle ':omz:plugins:eza' 'dirs-first' yes
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'header' yes
zstyle ':omz:plugins:eza' 'show-group' yes
zstyle ':omz:plugins:eza' 'color-scale' all

## python omz plugin
export PYTHON_AUTO_VRUN=true
export PYTHON_VENV_NAME='.venv'
export PYTHON_VENV_NAMES=('.venv' 'venv')

## zsh autosuggest plugin
typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=12,bold,underline"
typeset -g ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

## z setting
ZSHZ_TILDE=1

## custom plugin auto update
export UPDATE_ZSH_DAYS=30

## fzf-tab seetings
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-pad 0 0
zstyle ':fzf-tab:*' popup-min-size 80 20
zstyle ':fzf-tab:*' fzf-bindings-default "tab:toggle,btab:ignore,ctrl-space:ignore"
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:*' show-group
# To make fzf-tab follow FZF_DEFAULT_OPTS.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

######################### plugin settings ########################
source $ZSH/oh-my-zsh.sh
unsetopt correct_all
unsetopt correct

######################### User configuration #####################
# Redraw when window size changes
TRAPWINCH() {
	zle && { zle reset-prompt; zle -R }
}

# Auto url encode
zle -N self-insert url-quote-magic

# key bindings
bindkey '^B' backward-word
bindkey '^F' forward-word

# User specific aliases and functions
[ -f ${HOME}/.config/env/alias.sh ] && . ${HOME}/.config/env/alias.sh

# yazi shell wrapper
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

# p10k instant prompt
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
######################### User configuration #####################

# fzf config
[ -f "${DOTFILE_CLONE_PATH:-${HOME}/Github}/fzf_git/fzf-git.sh" ] && source "${DOTFILE_CLONE_PATH:-${HOME}/Github}/fzf_git/fzf-git.sh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
