# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

######################################
# @Author      : caodaqian
# @since       : 2020-09-09 10:41:33
# @LastEditors : caodaqian
# @lastTime    : 2020-09-09 13:56:59
# @Description : .zshrc
######################################

# init
echo -ne "\e[5 q"
export TERM=xterm-256color
export TERM_ITALICS=true
export CLICOLOR=1

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
ZSH_THEME="powerlevel10k/powerlevel10k"
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern'

# zsh features switch
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="false"
export UPDATE_ZSH_DAYS=13
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="false"
HIST_STAMPS="yyyy-mm-dd"
ZSH_CUSTOM=$ZSH/custom
setopt AUTO_CD
#setopt INTERACTIVE_COMMENTS
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY
setopt ALWAYS_TO_END
setopt COMPLETE_IN_WORD
setopt PROMPT_SUBST
setopt AUTO_MENU
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history

# User locale config
[ -f ${HOME}/.config/locale.sh ] && . ${HOME}/.config/locale.sh

# User specific aliases and functions
[ -f ${HOME}/.config/alias.sh ] && . ${HOME}/.config/alias.sh

# env config
[ -f ${HOME}/.config/env.sh ] && . ${HOME}/.config/env.sh
zle -N find-in-file
export DEFAULT_USER=$USER
export MANPATH="/usr/local/man:$MANPATH"
export SSH_KEY_PATH="~/.ssh/rsa_id"

plugins=(
	command-not-found
	common-aliases
	git-open
	sudo
	thefuck
	vscode
	zsh-interactive-cd
    encode64
    git
    jsontools
    tmux
    urltools
    wd
    zsh-autosuggestions
    zsh-syntax-highlighting
)

ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

source $ZSH/oh-my-zsh.sh
unsetopt correct_all
unsetopt correct
# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish


# User configuration
TRAPWINCH() {
  zle && { zle reset-prompt; zle -R }
}


# fzf config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '^R' fzf-history-widget
bindkey '^T' fzf-file-widget
bindkey '^F' find-in-file
bindkey '^I' $fzf_default_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
